name: Build Docker Images

on: [push]

jobs:
  build:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x

      - name: Run install
        uses: borales/actions-yarn@v4
        working-directory: ./app
        with:
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        working-directory: ./app
        with:
          cmd: build
      # - name: copy file via ssh key
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.HOST }}
      #     username: ${{ secrets.USERNAME }}
      #     port: ${{ secrets.PORT }}
      #     key: ${{ secrets.KEY }}
      #     source: "tests/a.txt,tests/b.txt"
      #     target: "test"
  