name: Build Docker Images

on: [push]

jobs:
  build:
    name: Build and Push Docker images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 12.x
        uses: actions/setup-node@v3
        with:
          node-version: 12.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          dir: ./client
          cmd: install
      - name: Build production bundle
        uses: borales/actions-yarn@v4
        env:
          CI: ""
        with:
          dir: ./client
          cmd: build
      - name: copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          host: ec2-3-80-217-207.compute-1.amazonaws.com
          username: ubuntu
          key: ${{ secrets.AWS_TOKEN }}
          source: "client/build/*"
          target: "re-iyfd/build"
  